version: '3'
services:
  mongodb-service:
    image: mongo
    container_name: mongodb-service
    ports:
      - 27017:27017
    networks:
      - network_1
    volumes:
      - volume_1:/mongodb 
  backend:
    image: node-app
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - mongodb-service
    networks:
      - network_1
  frontend:
    image: react-app
    container_name: frontend
    ports:
      - 3000:80
    networks:
      - network_1
    depends_on:
      - backend
volumes:
  volume_1:
networks:
  network_1:
   driver: bridge